services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env        
    ports:
      - "5003:5003"
    depends_on:
      - mongodb 

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://16.176.228.248:5003/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend